// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AVO Performance Horse",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "AVO Performance Horse",
            targets: ["AppModule"],
            bundleIdentifier: "com.avoperformance.horse",
            teamIdentifier: "4J2D6P5BJX",
            displayVersion: "1.2.1",
            bundleVersion: "34",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .mediaLibrary(purposeString: "La app necesita acceso a la biblioteca multimedia para importar, exportar y guardar vídeos e imágenes de análisis biomecánico equino."),
                .camera(purposeString: "La app utiliza la cámara para capturar vídeos y datos biomecánicos del caballo durante las sesiones de entrenamiento y análisis."),
                .bluetoothAlways(purposeString: "La app utiliza Bluetooth para conectarse con sensores externos y dispositivos de telemetría equina."),
                .localNetwork(purposeString: "La app utiliza la red para sincronizar datos con el servidor y dispositivos de análisis en tiempo real."),
                .locationWhenInUse(purposeString: "La app necesita la ubicación para mostrar el caballo en el mapa, controlar geocercas de entrenamiento y registrar sesiones GPS/RTK en tiempo real."),
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ],
            appCategory: .business
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("AVOHorsePose.mlpackage"),
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
